# configs/models/coastal_raster.toml

[model]
executor_module = "brmangue.executor"
name    = "brmangue"
class   = "brmangue"
package = "git+https://github.com/dissmodel/brmangue-dissmodel@develop"

[model.parameters]
end_time      = 88
taxa_elevacao = 0.5
altura_mare   = 6.0
acrecao_ativa = false
resolution    = 100.0
crs           = "EPSG:31984"
