
[model]
executor_module = "disslucc.infra.executors" 
name  = "lucc_vector"
class = "lucc_vector"
package = "git+https://github.com/dissmodel/disslucc-continuous@develop"


[model.parameters]
resolution = 5000.0
n_steps    = 7

land_use_types   = ["f", "d", "outros"]
land_use_no_data = "outros"
complementar_lu  = "f"
cell_area        = 25.0

[model.driver_columns]
cols = ["assentamen", "uc_us", "uc_pi", "ti", "dist_riobr", "fertilidad", "rodovias"]

[model.static]
f      = -1
d      = -1
outros = 1

[[model.potential]]
lu    = "f"
const = 0.7392
  [model.potential.betas]
  assentamen = -0.2193
  uc_us      =  0.1754
  uc_pi      =  0.09708
  ti         =  0.1207
  dist_riobr =  0.0000002388
  fertilidad = -0.1313

[[model.potential]]
lu    = "d"
const = 0.267
  [model.potential.betas]
  rodovias   = -0.0000009922
  assentamen =  0.2294
  uc_us      = -0.09867
  dist_riobr = -0.0000003216
  fertilidad =  0.1281

[[model.potential]]
lu    = "outros"
const = 0.0

[[model.allocation]]
lu = "f"
static = -1
min_value = 0
max_value = 1
min_change = 0
max_change = 1

[[model.allocation]]
lu = "d"
static = -1
min_value = 0
max_value = 1
min_change = 0
max_change = 1

[[model.allocation]]
lu = "outros"
static = 1
min_value = 0
max_value = 1
min_change = 0
max_change = 1